/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#c3c0ff",
        "on-secondary": "#213145",
        "inverse-surface": "#dae2fd",
        "tertiary": "#ffb784",
        "surface-container-high": "#222a3d",
        "on-background": "#dae2fd",
        "on-primary": "#1d00a5",
        "on-tertiary-container": "#ffc7a2",
        "surface-dim": "#0b1326",
        "on-tertiary": "#502500",
        "secondary-fixed": "#d3e4fe",
        "tertiary-fixed-dim": "#ffb784",
        "inverse-on-surface": "#283044",
        "surface-container-lowest": "#060e20",
        "surface-tint": "#c3c0ff",
        "secondary-container": "#3a4a5f",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-surface-variant": "#c5c5d4",
        "inverse-primary": "#4d44e3",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-highest": "#2d3449",
        "secondary": "#b7c8e1",
        "on-primary-container": "#d0cdff",
        "surface": "#0b1326",
        "on-secondary-fixed-variant": "#38485d",
        "surface-bright": "#31394d",
        "tertiary-container": "#8f4700",
        "outline-variant": "#454652",
        "on-tertiary-fixed": "#301400",
        "outline": "#8f909e",
        "primary-fixed-dim": "#c3c0ff",
        "primary-container": "#493fdf",
        "primary-fixed": "#e2dfff",
        "error": "#ffb4ab",
        "surface-container-low": "#131b2e",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary-container": "#a9bad3",
        "background": "#0b1326",
        "tertiary-fixed": "#ffdcc6",
        "on-primary-fixed": "#0f0069",
        "on-tertiary-fixed-variant": "#713700",
        "surface-variant": "#2d3449",
        "on-secondary-fixed": "#0b1c30",
        "on-surface": "#dae2fd",
        "surface-container": "#171f33"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
